# Dockerfile pour le service dashboard
FROM python:3.9

# Définir le répertoire de travail
WORKDIR /app

# Copier les fichiers nécessaires pour le dashboard
COPY requirements.txt ./
COPY dashboard.py ./

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Exposer le port 8050 (par défaut pour Dash)
EXPOSE 8050

# Lancer le dashboard
CMD ["python", "dashboard.py"]

